syntax on
set number
set relativenumber
set cursorline
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set scrolloff=8
set signcolumn=yes
set colorcolumn=80
set wildmenu
set wildmode=longest:full,full
colorscheme default
